name: Sync fork

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # At 00:00.

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git status
        git remote add upstream https://github.com/frozenpandaman/s3s.git
        git remote -v
        git fetch upstream
        git checkout master
        git rebase upstream/master
        git push -f origin master
        git remote remove upstream
        git remote -v